spring:
   datasource:
      generate-unique-name: false
      name: my-test-db
      url: jdbc:h2:mem:my-test-db
      username: S13075
      password: S13075
      hikari:
         connection-test-query: SELECT 1

   jpa:
      database: H2
      show-sql: true
      generate-ddl: true
      hibernate:
         dll-auto: validate
      #?adowanie danych pocz?tkowych po incjalizacji hibernate
      defer-datasource-initialization: true


   sql:
     init:
        mode: always
        platform: h2
logging:
   level:
      root: info

#endpoints values
my-api:
   baseURL: http://localhost:8080
   version: /api/v1
   applications: /applications
   permissionsChange: /permissionsChange
   permissionsRequest: /permissionsRequest
   reconciliation: /reconciliation
   justification: /justification


